#!/bin/bash

TARGET=create_launcher_icon
SRCS=create_launcher_icon.c
CFLAGS="-Wall -Werror -Wno-unused-result -Wno-format-truncation -Wno-unused-but-set-variable"
CFLAGS="$CFLAGS   -I . -I ../../../linux/local/include"
LIB_PATH=$(pwd)/../../../linux/local/lib
LIBS="-lezapp_lib -lmp3lame -llodepng -lcJSON -lkissfft-float -lSDL3 -lSDL3_ttf -lSDL3_mixer -lm"

# compile
(set -x; gcc -o $TARGET $CFLAGS $SRCS -L $LIB_PATH $LIBS -Wl,-rpath,$LIB_PATH)
if [ $? -ne 0 ]; then
    echo "ERROR: gcc failed"
    exit 1
fi

# run
./create_launcher_icon

# cleanup
rm create_launcher_icon

