TESTS=	00_assignment.test \
	01_comment.test \
	02_printf.test \
	03_struct.test \
	04_for.test \
	05_array.test \
	06_case.test \
	07_function.test \
	08_while.test \
	09_do_while.test \
	10_pointer.test \
	11_precedence.test \
	12_hashdefine.test \
	13_integer_literals.test \
	14_if.test \
	15_recursion.test \
	16_nesting.test \
	17_enum.test \
	18_include.test \
	19_pointer_arithmetic.test \
	20_pointer_comparison.test \
	21_char_array.test \
	22_floating_point.test \
	23_type_coercion.test \
	24_math_library.test \
	25_quicksort.test \
	26_character_constants.test \
	28_strings.test \
	29_array_address.test \
	30_hanoi.test \
	31_args.test \
	33_ternary_op.test \
	34_array_assignment.test \
	35_sizeof.test \
	36_array_initializers.test \
	37_sprintf.test \
	38_multiple_array_index.test \
	39_typedef.test \
	40_stdio.test \
	41_hashif.test \
	43_void_param.test \
	44_scoped_declarations.test \
	45_empty_for.test \
	47_switch_return.test \
	48_nested_break.test \
	49_bracket_evaluation.test \
	50_logical_second_arg.test \
	51_static.test \
	52_unnamed_enum.test \
	54_goto.test \
	55_array_initializer.test \
	56_cross_structure.test \
	57_macro_bug.test \
	58_return_outside.test \
	59_break_before_loop.test \
	60_local_vars.test \
	61_initializers.test \
	62_float.test \
	63_typedef.test \
	64_double_prefix_op.test \
	66_printf_undefined.test \
	67_macro_crash.test \
	68_return.test \

NOT_WORKING = 	32_led.test

include csmith/Makefile
include jpoirier/Makefile

%.test: %.expect %.c
	@echo -n "Test: $*... "
	@if [ "x`echo $* | grep args`" != "x" ]; \
	then \
		../picoc $*.c - arg1 arg2 arg3 arg4 2>&1 >$*.output; \
	elif [ "x`echo $* | grep script`" != "x" ]; \
	then \
		../picoc -s $*.c 2>&1 >$*.output; \
	else \
		../picoc $*.c 2>&1 >$*.output; \
	fi
	@if [ "x`diff -qbu $*.expect $*.output`" != "x" ]; \
	then \
        	echo "********** FAILED **********"; \
        	diff -y $*.expect $*.output; \
		exit 1; \
	else \
        	echo "PASSED"; \
	fi; \
       	rm -f $*.output

all: test jpoirier csmith 

test: $(TESTS)
	@echo

csmith: $(CSMITH_TESTS)
	@echo

jpoirier: $(JPOIRIER_TESTS)
	@echo

# EZAPP tests follows,
# These differs from the baseline tests in that the ezapp tests
# generate the expect file on every invokation.

EZAPP_TESTS = 100_printf \
              101_ternary_op \
              102_statics \
              103_cast \
              104_ops \
              105_sizeof \
              106_ifdef

ezapp: $(EZAPP_TESTS)
	@echo

$(EZAPP_TESTS):
	@echo -n "Test: $@ ... "
	@gcc -o /tmp/$@ -Wall -Werror $@.c
	@/tmp/$@ > $@.expect
	@rm /tmp/$@
	@../picoc $@.c 2>&1 > $@.output
	@cmp -s $@.expect $@.output; \
        if [ $$? != 0 ]; then \
            echo "********** FAILED **********"; \
            diff --side-by-side $@.expect $@.output; \
            exit 0; \
        else \
            rm -f $@.expect $@.output; \
            echo "PASSED"; \
        fi

clean:
	rm -f *.output
	git ls-files --others *.expect | xargs rm -f

.PHONY: $(EZAPP_TESTS) clean
