SHAID_TESTS = shaid/100_printf \
              shaid/101_ternary_op \
              shaid/102_statics \
              shaid/103_cast \
              shaid/104_ops \
              shaid/105_sizeof \
              shaid/106_ifdef

